### ISSUE TITLE
Kernelsu

### ISSUE THREAD

**Issue by luyanci** [UnicomAndroid/Android-Builder#20]
https://github.com/tiann/KernelSU/commit/898e9d4f8ca9b2f46b0c6b36b80a872b5b88d899
kernelsu从v1.0.0版本开始(或从这条commit开始)，不再支持*非gki内核*，可能导致后面的内核构建会出错

**Comment by easterNday** [comment]
PR plz, thank u.

**Comment by easterNday** [comment]
What is the current development of APatch, or do I have other better root methods?
