### ISSUE TITLE
[Suggestion] Use maximize build space

### ISSUE THREAD

**Issue by Lu5ck** [UnicomAndroid/Android-Builder#6]
Might want to consider using this https://github.com/easimon/maximize-build-space to maximize the available build space, it also able to increase swap size after maximizing space.

**Comment by easterNday** [comment]
Thanks for your suggestion, I will try it and let me know if you have any more suggestions.

**Comment by easterNday** [comment]
Thank you for your suggestion. I have used this Action to expand and adjust the storage space and swap space.
